name: Backport
'on':
  pull_request_target:
    types:
    - closed
    - labeled
permissions:
  contents: read
jobs:
  backport:
    permissions:
      contents: write
      pull-requests: write
    name: Backport Pull Request
    if: github.repository_owner == 'wdrx70xn' && github.event.pull_request.merged
      == true && (github.event_name != 'labeled' || startsWith('backport', github.event.label.name))
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        persist-credentials: true
    - name: Create backport PRs
      uses: korthout/backport-action@3c06f323a58619da1e8522229ebc8d5de2633e46
      with:
        branch_name: backport/${pull_number}-to-${target_branch}
        copy_labels_pattern: severity:\ssecurity
        pull_description: 'Bot-based backport to `${target_branch}`, triggered by
          a label in #${pull_number}.'
