name: Docs linkcheck
'on':
  workflow_dispatch: null
  schedule:
  - cron: 0 7 * * 1
permissions:
  contents: read
concurrency:
  group: docs-linkcheck
  cancel-in-progress: true
jobs:
  linkcheck:
    if: github.repository_owner == 'wdrx70xn'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        persist-credentials: false
    - uses: nixbuild/nix-quick-install-action@2c9db80fb984ceb1bcaa77cdda3fdf8cfba92035
    - name: Check docs links
      run: nix run --print-build-logs '.#ci-scripts/docs-linkcheck'
